version: '3'
services:
  db:
    image: postgres:11.2
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    container_name: open-weather-db
    environment:
      - POSTGRES_PASSWORD=password
  web:
    build: .
    env_file: .env
    container_name: open-weather-web
    volumes:
      - .:/open-weather-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
    command: >
      bash -c "bundle exec rake db:create &&
               bundle exec rake db:migrate &&
               rm tmp/pids/server.pid -f &&
               bundle exec rails s -b 0.0.0.0 -p 3000"
