default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: open-weather-development

test:
  <<: *default
  database: open-weather-test
